version: "3.9"
services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: whatsapp_crm
      MARIADB_USER: app
      MARIADB_PASSWORD: app
    ports: ["3306:3306"]
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  api:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: whatsapp_crm
      JWT_SECRET: dev-secret
      WHATSAPP_API_URL: http://your-wa-gateway
      WHATSAPP_API_TOKEN: dev-token
      WHATSAPP_WEBHOOK_VERIFY_TOKEN: verify-token
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 8080
    depends_on: [db, redis]
    ports: ["8080:8080"]
volumes:
  db_data:
